In [1]:
import mrob
import numpy as np

In [24]:
graph = mrob.FGraph()
#help(graph.add_node_pose_3d)
T = mrob.geometry.SE3(np.random.randn(6))
print('initial random pose = \n',T.T())
n1 = graph.add_node_pose_3d(T)
print('node = ', n1)

# anchor factor
W_0 = np.identity(6)
# help(graph.add_factor_1pose_3d)
graph.add_factor_1pose_3d(mrob.geometry.SE3(),n1,W_0)

# add a landmark observation
W = np.identity(3)
l1 = graph.add_node_landmark_3d(np.zeros(3))
obs = np.array([1,0,0])
graph.add_factor_1pose_1landmark_3d(obs,n1,l1,W)
print(graph.get_estimated_state())

print('Initial chi2 = ' , graph.chi2())
with mrob.ostream_redirect():
    graph.solve(mrob.LM)
    print('chi2 = ' , graph.chi2())
    graph.print(True)
    pass

initial random pose = 
 [[ 0.04705724  0.9876998   0.14911314 -1.09255086]
 [-0.18335888  0.15528313 -0.97070421 -1.37645028]
 [-0.98191911  0.01833744  0.18841072  1.83838781]
 [ 0.          0.          0.          1.        ]]
node =  0
[array([[ 0.04705724,  0.9876998 ,  0.14911314, -1.09255086],
       [-0.18335888,  0.15528313, -0.97070421, -1.37645028],
       [-0.98191911,  0.01833744,  0.18841072,  1.83838781],
       [ 0.        ,  0.        ,  0.        ,  1.        ]]), array([[0.],
       [0.],
       [0.]])]
Initial chi2 =  7.157277496678136

FGraphSolve::optimize_levenberg_marquardt: iteration 1 lambda = 1e-05, error 7.15728, and delta = 6.40398
model fidelity = 0.894758 and m_k = 14.3144

FGraphSolve::optimize_levenberg_marquardt: iteration 2 lambda = 2.5e-06, error 0.753293, and delta = 0.753293
model fidelity = 1 and m_k = 1.50658

FGraphSolve::optimize_levenberg_marquardt: iteration 3 lambda = 6.25e-07, error 2.26179e-10, and delta = 2.26179e-10
chi2 =  1.208804346305